apiVersion: v1
kind: Service
metadata:
  name: libredb-studio
  namespace: libredb-studio
spec:
  type: ClusterIP
  selector:
    app: libredb-studio
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
